name: branches

on:
  push:
    branches: "*"

jobs:

  test:
    runs-on: alpine-latest
    steps:

      - name: "checkout"
        uses: actions/checkout@v4.1.1

      - name: "setup-go"
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: "compile"
        run: make build

      - name: "unit tests"
        run: make test

      - name: "test coverage"
        run: make cover
